import 'package:flutter/material.dart';
import 'package:hive/hive.dart';

part 'MeetingHive.g.dart'; // This will be generated by build_runner

@HiveType(typeId: 0)
class MeetingHive {
  @HiveField(0)
  String title;

  @HiveField(1)
  DateTime date;

  @HiveField(2)
  String name;

  @HiveField(3)
  String meetingId;

  @HiveField(4)
  String location;

  @HiveField(5)
  int startTimeHour;

  @HiveField(6)
  int endTimeHour;

  @HiveField(7)
  bool isFirstMeetingAtClient;

  @HiveField(8)
  double distance;

  @HiveField(9)
  double expectedPayment;

  @HiveField(10)
  bool isReported;

  @HiveField(11)
  String notes;

  @HiveField(12)
  bool isDeleteed;

  @HiveField(13)
  int startTimeMinute;

  @HiveField(14)
  int endTimeMinute;

  MeetingHive({
    required this.title,
    required this.date,
    required this.name,
    required this.meetingId,
    required this.location,
    required this.startTimeHour,
    required this.endTimeHour,
    required this.endTimeMinute,
    required this.startTimeMinute,
    required this.isFirstMeetingAtClient,
    required this.distance,
    required this.expectedPayment,
    required this.isReported,
    required this.notes,
    required this.isDeleteed,
  });
}
